# Generated by Django 3.1.1 on 2020-10-06 15:10

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=15)),
                ('gst', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('productname', models.CharField(max_length=15)),
                ('cost', models.IntegerField(blank=True, default=10)),
                ('companies', models.ForeignKey(default=True, on_delete=django.db.models.deletion.CASCADE, to='webapp3.company')),
            ],
        ),
        migrations.CreateModel(
            name='order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cost', models.IntegerField(blank=True, default=10)),
                ('quantity', models.IntegerField(default=1)),
                ('totalprice', models.IntegerField(blank=True, default=10)),
                ('order_no', models.IntegerField(default=1)),
                ('purchased_ON', models.DateTimeField(default=datetime.datetime.now)),
                ('purchase_details', models.CharField(blank=True, max_length=50)),
                ('companies', models.ForeignKey(default=True, on_delete=django.db.models.deletion.CASCADE, to='webapp3.company')),
                ('productname', models.ForeignKey(default=True, on_delete=django.db.models.deletion.CASCADE, to='webapp3.product')),
            ],
        ),
    ]
