# Generated by Django 3.1.1 on 2020-10-08 06:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp3', '0002_auto_20201007_2307'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='purchased_ON',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
