# Generated by Django 3.1.1 on 2020-10-08 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp3', '0003_auto_20201007_2312'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='purchased_ON',
            field=models.DateField(null=True),
        ),
    ]
